### ISSUE TITLE
How to specify Volumes (map[string]struct{})?

### ISSUE THREAD

**Issue by drnic** [fsouza/go-dockerclient#155]
Sorry for the babygopher question, but cannot find an example in the test cases or docs or google.

containers.go `Config` defines `Volumes  map[string]struct{}`.

How do I pass in the equivalent to `docker run -v /host/path:/inner`?

`struct{}` seems to be the equivalent of "no value" - so I'm not sure how to pass in `{"/host/path": "/inner"}`

Ideas?

**Comment by Setomidor** [comment]
I suppose you've already figured this out by now, but for other people who may stumble upon this:

What you are trying to do is mixing Volumes and Binds:
- For  "/myworkdir" you want to use volumes as this simply exposes this endpoint as a "non-UnionFS" mount point (in an anonymous location, in your case the thing starting /var/lib/docker/vfs/dir/..).
- For "/root/.ssh" you want to use binds as this creates a bind between the container and the fixed location "/root.ssh" on your host machine.

Send the Binds argument to the HostConfig (since this can only be done when deploying an actual container instance on an actual host), and send the Volumes argument to the container Config when creating this Container (as the exposed mount points are linked to the container, and not the instance).

This links contains a great explanation about wha volumes are and how they work: http://container-solutions.com/2014/12/understanding-volumes-docker/

**Comment by mieubrisse** [comment]
I'm having the same problem as the original poster, but I'm using named volumes rather than bind mounts. I'm confused about why the value type of Volumes is a `struct{}`, and what I should be passing in as the value. Should that be the Volume object that comes back from CreateVolume?
