### ISSUE TITLE
Malformed response from Docker daemon

### ISSUE THREAD

**Issue by josephschorr** [fsouza/go-dockerclient#166]
Just upgraded to Docker v1.3. When I try to issue a call to the Docker daemon via the client, the daemon responds with a malformed response:

```
Post http://192.168.59.103:2376/images/create?fromImage=mynamespace%2Fmyrepo&registry=localhost:6060&tag=latest
```

Response:

```
 malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"
```

I suspect this is due to the new TLS requirement for the Docker daemon, but I'm unsure how to configure the client to use https.

**Comment by matthieudelaro** [comment]
Actually, there is one more thing to do if you want your docker client to be able to attach to a container. Since attaching to a container works partially in binary (a part of the process is not un pure HTTP), setting the parameters of the https transport is not enough.

So you have to add something like:
```go
c.TLSConfig = conf
```

Unfortunately I did not save the exact code, because in Nut I replaced everything with:
```go
docker.NewClientFromEnv()
```
([full code](https://github.com/matthieudelaro/nut/blob/master/network.go#L27))
This very nice function [included](https://github.com/fsouza/go-dockerclient/blob/9d5fef7969a53796f7405827c3e68804f533b1ee/client.go#L237) in `go-dockerclient` does all the job for you. There are even some similar functions in the same file, for which you can specify the keys you want to use, etc.
