### ISSUE TITLE
clean up (--rm) support

### ISSUE THREAD

**Issue by drewwells** [fsouza/go-dockerclient#250]
Is it possible to pass along clean up options to docker? The docker API doesn't list a clean up config: http://goo.gl/iM5GYs, but the cli very clearly does have this feature.

**Comment by fsouza** [comment]
Hi @drewwells, thanks for opening this issue. There's no option for that in the API because Docker client handles it (that's why it is incompatible with the ``-d`` flag), because it needs to detect that the container exited.

Here's the code: https://github.com/docker/docker/blob/master/api/client/run.go#L184:L190

You'd need to do something like that in your code that uses go-dockerclient.
