### ISSUE TITLE
Can't stop the Stats function via Done channel

### ISSUE THREAD

**Issue by Cerfoglg** [fsouza/go-dockerclient#423]
I'm currently experiencing an issue with the Stats function https://godoc.org/github.com/fsouza/go-dockerclient#Client.Stats

According to the doc, this function is blocking, and only stops when the container it's attached to is removed, or when you signal on the Done channel, which can be specified in the StatsOptions you pass to the function https://godoc.org/github.com/fsouza/go-dockerclient#StatsOptions

When I try to send anything on the Done channel however, I get a "io: read/write on closed pipe" error. Here I'm providing a simple example that causes this to happen. This might be a bug in the API.

Here I'm attaching to a container called db:

``` golang
func main() {
    endpoint := "unix:///var/run/docker.sock"
    client, err := docker.NewClient(endpoint)
    if err != nil {
        log.Fatal(err)
        }
    stats := make(chan *docker.Stats)
    done := make(chan bool)
    var wg sync.WaitGroup
    wg.Add(1)
    go func() {
        err := client.Stats(docker.StatsOptions{
            ID:      "db",
            Stats:   stats,
            Stream:  true,
            Done:    done,
            Timeout: time.Duration(10),
        })
        if err != nil {
            log.Fatal(err)
        }
        fmt.Println("I'm done")
        wg.Done()
    }()
    done <- true
    wg.Wait()
}
```

**Comment by Cerfoglg** [comment]
I eventually found out that the function does stop when sending a value on the Done channel (or closing the channel altogether), but it does return an error when doing so. If I catch the error and don't do log.Fatal I can just ignore the error, though it would be best if the Stats function did not return an error when attempting to stop it.

**Comment by fsouza** [comment]
@Cerfoglg which error you're getting?

**Comment by Cerfoglg** [comment]
@fsouza The error is "io: read/write on closed pipe" as it appears in the log, which I believe corresponds to ErrClosedPipe in io https://golang.org/pkg/io/

**Comment by nikhilm** [comment]
Bringing up an old issue since we've been experiencing spurious errors due to this.
Closing the `Done` channel passed to `StatsOptions` immediately closes the read end of the pipe here - https://github.com/fsouza/go-dockerclient/blob/master/container.go#L1025.

Further reads from the json decoder, or attempts to write to the write end will result in io.ErrClosedPipe, which is what gets returned. I'm not sure what a clean way to fix this is, since there are 3 goroutines in Stats() and `stream()` also spawns some. If you can suggest something, happy to send in a PR. Reduced test case of Read() following a Close() returning this error - https://play.golang.org/p/54QucwTDCW

**Comment by nikhilm** [comment]
Also, I guess a better description of this issue is "Stopping the Stats() function via Done channel leads to bad reads from pipe and spurious errors."
