### ISSUE TITLE
How does one create a container with the equivalent of `-v` option? 

### ISSUE THREAD

**Issue by allan-simon** [fsouza/go-dockerclient#445]
I'm using the  `CreateContainerOptions`  methods to create containers,  I would like all my containers to have the same `/etc/ssl/certs/ca-certificates.crt`  

in the documentation I can see that https://godoc.org/github.com/fsouza/go-dockerclient#Config has a field `Volumes`  but what is bizarre is that it's a `map[string]struct{}`  and I can't find anywhere what is this `struct{}` supposed to be , as all the tests in the repository initialize it with `{}` 

Would be it possible to be provided with an example? thanks :)

**Comment by fsouza** [comment]
Hi @allan-simon, you should look for the Mounts field, in the Config struct. The code is indeed bizarre/ugly because of some changes in the Docker API. I apologize for that, but the client must remain backward compatible to prevent breaking code from users of the library.

What I think we should have is a test in the integration tests suite creates a file in some shared volume and confirm that it's accessible in the container. This test would ensure that things work and could also be used as documentation of the feature.

I will keep this issue open for handling that. Thanks for raising it.

**Comment by allan-simon** [comment]
no problem, I understand it's not always easy, especially as an opensource project to keep track with API from other project that move at quite fast pace.

I will try to find how to use the Mounts field

**Comment by raphink** [comment]
@allan-simon have a look at https://github.com/camptocamp/conplicity/blob/master/conplicity.go#L137-L143

**Comment by allan-simon** [comment]
@raphink , ah nice thanks :)

**Comment by noqcks** [comment]
Im unable to create a mount.

```
> docker -v
Docker version 1.12.3, build 6b644ec
```

config currently looks like this
```
	container, err := client.CreateContainer(docker.CreateContainerOptions{
		Config: &docker.Config{
			Image: "ubuntu",
			Mounts: []docker.Mount{docker.Mount{
				Source:      "/",
				Destination: "/mount",
				RW:          true,
			}}
		}
	})
```

@raphink I believe your repo changed a little. Do you have an updated code example? thanks.

**Comment by raphink** [comment]
@noqcks in case that's useful, I now migrated conplicity to the official go Docker library, which works well.
