### ISSUE TITLE
1.22 Events Format Change

### ISSUE THREAD

**Issue by schmatz** [fsouza/go-dockerclient#471]
The events fields have changed from [1.21](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#monitor-docker-s-events) to [1.22](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#monitor-docker-s-events). Are there plans to change the `APIEvents` fields accordingly?

**Comment by fsouza** [comment]
Yes, but we should keep go-dockerclient compatible with older versions of the API as well.

**Comment by nickvanw** [comment]
Hey @fsouza! I'm looking at picking up changing the `APIEvents` over to use the new schema in 1.22, but I'm having a hard time picturing how to make sure it's backwards compatible with 1.21 and prior versions. 

Because the Docker API change involves adding additional events, as well as radically changing the schema, trying to shoehorn information into a backwards compatible struct feels like it would only cause confusion and create a lot of cruft in the `go-dockerclient` API. 

Any opinions/ideas? cc @schmatz

**Comment by schmatz** [comment]
We might be able update the struct to reflect the new API but translate events from the older APIs to fit in the new struct, with pointers to fields that may not exist for older versions of the API. It might be possible to do this transparently. I haven't had the time to look into this in depth, so I defer to the judgement of @fsouza.

If there are a ton of new features that also exhibit the same backwards compatibility issues and changing the library dramatically isn't an option, might be best to make a fork.

**Comment by nickvanw** [comment]
If anyone is looking for this ASAP and doesn't need backwards compatibility, https://github.com/nickvanw/go-dockerclient/commit/0dd806834d0002ea156de70ee2f59979f75fc1d7 should get you what you're looking for. I haven't extensively tested it, but it should work.

**Comment by fsouza** [comment]
Closing, as #477 has been merged. @nickvanw, thanks for working on that!
