### ISSUE TITLE
Streaming not possible with BuildImage

### ISSUE THREAD

**Issue by tnine** [fsouza/go-dockerclient#479]
I may be wrong on this, so feel free to correct me.  I've written a simple test that tests building an image, then piping the buffer of the build to stdout.  It appears the log is completely buffered in memory before io.Copy is invoked.  See this code.

https://github.com/30x/shipyard/blob/master/shipyard/docker.go#L79

When invoking it via the test, I see the following output.

    INFO: 2016/03/08 23:40:56 docker.go:83: Started uploading image with name test6cf7c784-291d-42dc-5697-83064328dca9/test:v1.0 and tar file /tmp/shipyard/22583bff-05d8-4f55-5e7c-87d7d6384053/docker-data.tar

    INFO: 2016/03/08 23:40:56 docker.go:106: Completed uploading image with name test6cf7c784-291d-42dc-5697-83064328dca9/test:v1.0 and tar file /tmp/shipyard/22583bff-05d8-4f55-5e7c-87d7d6384053/docker-data.tar

I then see the buffer output after the build image call returns with no error.  Is it possible to return a stream that can be piped as the image is being built?  With large images, or images that have several layers to pull, there is not output to confirm work is occurring.

**Comment by nickvanw** [comment]
Hey @tnine! If I'm looking at the right code in shipyard (I think the line numbers have shifted down), it looks like they're setting an output buffer, but then not reading it until after the `BuildImage` call has returned. Because that method is blocking, by the time it's returned you'll have already completed the image building.

Try launching a goroutine before calling `BuildImage` that reads and prints from the `outputBuffer`, if I'm reading the `stream()` implementation inside of `go-dockerclient`, I believe that will actually stream the output while the call is occurring.

**Comment by tnine** [comment]
Thanks for the reply @nickvanw.  As a test, I've tried changing my outputBuffer to simply be stdout.  I would expect this to stream as the API call is being made, however, I only get the results at the end.  For instance, I change my outputBuffer in the following way.

`outputBuffer := os.Stdout`

Is the response.Body buffered in the c.stream invocation here before io.Copy is invoked?  

https://github.com/fsouza/go-dockerclient/blob/73f08fbacc09c6fd1b7bc179193e58b14d7619cc/client.go#L540

Its the only thing I can think of that would explain the behavior I'm seeing if I pass os.Stdout as the output stream.

**Comment by tnine** [comment]
Disregard.  PEBKAC.
