### ISSUE TITLE
Event subscription can fail silently

### ISSUE THREAD

**Issue by awh** [fsouza/go-dockerclient#485]
Under certain circumstances the event subscription mechanism silently stops delivering events:
- If an EOF is received from the event request body by `eventHijack`
- If `connectWithRetry` fails more than five times

We are experiencing the first case here weaveworks/weave#2016.

**Comment by nickvanw** [comment]
Hey @awh! 

I've experienced this issue as well - specifically

> it's getting an EOF immediately on trying to decode the first event.

I was able to work around this (and other errors) by listening to the channel's boolean response here: https://github.com/nickvanw/docker-proxy/blob/master/manager.go#L96-L100 - when this happens, the channel will have been closed, and you can re-create the listener. 

I would love to make a longer-term fix for this bug, but I think it should be considered a "best practice" to make sure the channel is open, otherwise you run the risk of missing errors.
