### ISSUE TITLE
Docker 1.11 & Docker Remote API v1.23

### ISSUE THREAD

**Issue by nickvanw** [fsouza/go-dockerclient#500]
It looks like 1.11 and a corresponding API update has been released.

The specifics on the API changes: https://docs.docker.com/engine/reference/api/docker_remote_api/#v1-23-api-changes

Over the next week or so, I'm going to try and get as many of the changes in as possible. If anyone else is interested in helping with the work, post here and we can coordinate.

**Comment by paulcadman** [comment]
I'm willing to help with this.

**Comment by peter-edge** [comment]
A checklist for things that are changed, check them off once you have a PR in review or if the task was already completed previously:

- [ ] GET /containers/json returns the state of the container, one of created, restarting, running, paused, - [ ] exited or dead.
- [ ] GET /containers/json returns the mount points for the container.
- [ ] GET /networks/(name) now returns an Internal field showing whether the network is internal or not.
- [ ] GET /networks/(name) now returns an EnableIPv6 field showing whether the network has ipv6 enabled or not.
- [ ] POST /containers/(name)/update now supports updating container’s restart policy.
- [ ] POST /networks/create now supports enabling ipv6 on the network by setting the EnableIPv6 field (doing this with a label will no longer work).
- [ ] GET /info now returns CgroupDriver field showing what cgroup driver the daemon is using; cgroupfs or systemd.
- [ ] GET /info now returns KernelMemory field, showing if “kernel memory limit” is supported.
- [ ] POST /containers/create now takes PidsLimit field, if the kernel is >= 4.3 and the pids cgroup is supported.
- [ ] GET /containers/(id or name)/stats now returns pids_stats, if the kernel is >= 4.3 and the pids cgroup is supported.
- [ ] POST /containers/create now allows you to override usernamespaces remapping and use privileged options for the container.
- [ ] POST /containers/create now allows specifying nocopy for named volumes, which disables automatic copying from the container path to the volume.
- [ ] POST /auth now returns an IdentityToken when supported by a registry.
- [ ] POST /containers/create with both Hostname and Domainname fields specified will result in the container’s hostname being set to Hostname, rather than Hostname.Domainname.

**Comment by peter-edge** [comment]
https://github.com/fsouza/go-dockerclient/pull/502

**Comment by peter-edge** [comment]
@fsouza we have to decide what to do with `Client#CheckAuth`, which is the `POST /auth` API call. Before, there was no returned information, so the function just returns error, but now there is returned information, so we should return something like an `AuthStatus` struct, but this will break existing usage of this function.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#check-auth-configuration
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#check-auth-configuration
https://github.com/fsouza/go-dockerclient/blob/ce9c24137ce84061e63877400c5cc6f95b1d7d14/auth.go#L128

**Comment by nickvanw** [comment]
@peter-edge I'm not the maintainer of course, but I think a breaking change is appropriate here, otherwise we risk masking errors.

Longer term, what would you think about using something like http://labix.org/gopkg.in @fsouza? It would make adding breaking changes much easier.

**Comment by peter-edge** [comment]
I agree that a breaking change would be OK here.

I don't know about gopkg.in - so many people already have github.com/fsouza/go-dockerclient as their import path already, and I actually kind of like everyone either having to be up to date, or vendoring. I am less in favor of gopkg.in than I used to be :)

**Comment by nickvanw** [comment]
That's a fair point, it'd still be breaking no matter what for a large number of people. In reality, people should probably be using the vendoring introduced in 1.5 to avoid this problem

**Comment by peter-edge** [comment]
Anyways, it's more fun to run your own import server :) https://go.pedge.io https://go.pedge.io/importserver

**Comment by fsouza** [comment]
I agree that it's fair to take this breaking change in. I'm going to merge #502, then you work in the breaking change :-) 

Thanks for contributing! :-D

**Comment by peter-edge** [comment]
https://github.com/fsouza/go-dockerclient/pull/505

**Comment by nickvanw** [comment]
Thinking we can probably close this, kind of envious that @peter-edge got to implementation before I had time!

**Comment by fsouza** [comment]
@peter-edge @nickvanw @justone thank you for your awesome work in this issue :-D

**Comment by deepakprabhakara** [comment]
Just a quick query, I noticed that PidsLimit was added to Config, doesn't Remote API v1.23 need it in the HostConfig instead?

**Comment by fsouza** [comment]
Indeed, @deepakprabhakara. Pushing a fix.

I'll remove PidsLimit from Config, and if it affects someone, I add it back.

**Comment by deepakprabhakara** [comment]
Excellent, thank you @fsouza!
