### ISSUE TITLE
No client `Disconnect' method or auto-reconnection?

### ISSUE THREAD

**Issue by jaytaylor** [fsouza/go-dockerclient#518]
Here is what I am observing:

1. There is no way to disconnect a docker.Client (no `Close()' or similar).

2. When listening on the unix:///file socket and the docker system service gets restarted, the client does not reconnect itself.

3. Subsequent calls to docker.NewClient() then cause my program to quickly eat all available system memory when docker isn't running (rough estimate is ~50MB of memory is allocated per new client).

Is there some other way to gracefully recover in the scenario where the underlying client connection dies?

Also: What is going on  with the memory usage here?  50MB minimum is way too heavy for what I am trying to do.. is there a way to use go-dockerclient without paying such a high penalty in terms of memory resource footprint overhead?

**Comment by jaytaylor** [comment]
I've switched to the [possibly more up-to-date] [github.com/samalba/dockerclient](https://github.com/samalba/dockerclient) library and all the aforementioned issues has disappeared.

**Comment by fsouza** [comment]
Hi @jaytaylor, go-dockerclient doesn't have a "Close" because Docker API is plain-old-HTTP. Were you using latest master of go-dockerclient? If you have some code snippet that reproduces the issue, I'd like to work on it!

BTW, Docker offers an official client now: https://godoc.org/github.com/docker/engine-api/client.
