### ISSUE TITLE
add release version for diff docker/go version

### ISSUE THREAD

**Issue by upccup** [fsouza/go-dockerclient#661]
there has some reason that i have to use docker 1.9.1 which is build by go 1.4.3.  But there have some legacy version compatibility question with go. [Pre-golang 1.6 Dockers can't talk to golang 1.6 Docker](https://github.com/moby/moby/issues/20865). so i can only use go 1.4.3 to build this. But now that is hard to build with the master's code. 

is it possible to add some release tag for diff docker/go version?

**Comment by fsouza** [comment]
Hey @upccup, we can certainly do that! I'll try to dig up the versions compatible with Go 1.4, 1.5 and 1.6 and create the proper tags.

**Comment by upccup** [comment]
@fsouza  👍 👍

**Comment by fsouza** [comment]
@upccup turns out that tracking this down is pretty hard because of the dependencies. I was able to build go-dockerclient with Go 1.4 inside Docker, take a look at this Dockerfile: https://gist.github.com/fsouza/9b5ca9592795084c6fe96d660b16ba96

I created the tag and documented it in the README. Let me know if that works for you!

**Comment by upccup** [comment]
@fsouza  thks i will try asap
