### ISSUE TITLE
Tip is incompatible with latest release of docker

### ISSUE THREAD

**Issue by johanbrandhorst** [fsouza/go-dockerclient#678]
As commented on https://github.com/fsouza/go-dockerclient/pull/674, merging that pull means that this repo is only compatible with _master_ of docker/docker. This might be intentional, and please close if so.

**Comment by andrestc** [comment]
I'm not sure I'm following. How does **adding** a new endpoint breaks the compatibility with older versions? Isn't it just a matter of not using the new endpoints if you are on the previous version?

**Comment by johanbrandhorst** [comment]
This package is now importing a struct that doesn't exist in released versions of docker.

**Comment by johanbrandhorst** [comment]
To add a bit of context, the change started importing `"github.com/docker/docker/api/types/registry".DistributionInspect`, which does not exist on `17.05.x`: https://github.com/moby/moby/blob/17.05.x/api/types/registry/registry.go

**Comment by andrestc** [comment]
Oh, I see. I thought you were talking about the HTTP API compatibility.

I don't think we ever aimed to only depend released versions of docker (maybe we should?), so I'll leave this one to @fsouza.

**Comment by fsouza** [comment]
Hey @johanbrandhorst, thanks for opening this issue. In order to support latest Docker features and import their stuff, we need to use the master of [moby/moby](https://github.com/moby/moby/releases). Please notice that Docker is no longer released from ``moby/moby``, but [docker/docker-ce](https://github.com/docker/docker-ce/releases), so the latest release of Docker is not 17.05, but 17.09.

The alternative would be to copy the type definitions from Moby source code. But again, if you're sticking to tags on ``moby/moby``, you're not using the latest version of Docker.

**Comment by johanbrandhorst** [comment]
@fsouza Thanks for the update and explanation. So this repo uses `master` of https://github.com/moby/moby/releases, is that because those releases are old anyway? I can understand sticking to `master`, so I will close this issue.

**Comment by fsouza** [comment]
@johanbrandhorst thanks for understanding and raising the question in the first place! :D
