### ISSUE TITLE
Exec /bin/bash echoes stdin to stdout

### ISSUE THREAD

**Issue by jess-tang** [fsouza/go-dockerclient#707]
Hello, I have an issue running `/bin/sh` (also `/bin/zsh` and `/bin/bash`).

When I create, start and attach to a container using go-dockerclient, the input in stdin will be printed in the next line, for example,
```
# sh
sh-3.1$ hs
hs
sh: hs: command not found

#zsh
unix:///var/run/docker.sock$ uname
uname
Linux
```
This happened for all 3 shells. I also tried to run `/bin/sh` with `container.AttachToContainer` and `exec.StartExec`, and they both have this issue.

I also tried to set the command as
```
cmd := []string{"/bin/bash", "+x"}
```
but it is still not working.

However, when using command line, this problem doesn't occur.
```
 % docker exec -it 6089 /bin/sh
sh-3.1$ echo hello
hello
sh-3.1$
```
So my image should be fine.

My docker version is 
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Thu Jan 26 09:26:48 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Thu Jan 26 09:26:48 2017
 OS/Arch:      linux/amd64
```

This is my `CreateDockerConfig`:
```
docker.Config{
		Image:        image,
		Cmd:          cmd,
		Hostname:     dockerHost,
		Env:          env,
		User:         user,
		WorkingDir:   wdir,
		AttachStdout: true,
		AttachStderr: true,
		Tty:          true,
		AttachStdin:  true,
		OpenStdin:    true,
		StdinOnce:    true,
	}
```

This is my `AttachToContainerOptions`:
```
docker.AttachToContainerOptions{
		Container:    container,
		OutputStream: os.Stdout,
		ErrorStream:  os.Stderr,
		Stream:       true,
		RawTerminal:  true,
		Stdout:       true,
		Stderr:       true,
		Stdin:        true,
		InputStream:  os.Stdin,
	}
```

Is there anything I'm missing? Thank you!

**Comment by fsouza** [comment]
Hey @jess-tang, in order to accomplish that, you need to treat stdin as a raw terminal, similar to what the following tools do:

- ``docker exec``: https://github.com/docker/cli/blob/feb4d7993554f707a50ba9e57e8b2e996456753d/cli/command/container/hijack.go#L81-L83
- ``tsuru app-shell``: https://github.com/tsuru/tsuru/blob/048e9b342199ba83343cf02a92017dd4d44b1a51/cmd/shell.go#L58-L76
- ``kubectl exec``: https://github.com/kubernetes/kubernetes/blob/ed273fc9bbf2265c33922e2285eab7975754b040/pkg/kubectl/cmd/exec.go#L217-L267

Using [golang.org/x/crypto/ssh/terminal](https://godoc.org/golang.org/x/crypto/ssh/terminal) you could do the following before attaching to the container:

```go
fd := os.Stdin.Fd()
if terminal.IsTerminal(fd) {
	oldState, err := terminal.MakeRaw(fd)
	if err != nil {
		// handle err ...
	}
	defer terminal.Restore(fd, oldState)
}
```

**Comment by jess-tang** [comment]
It works great! Thank you so much!

**Comment by Nohac** [comment]
@jess-tang How did you get it to work? Can you post the code?
