### ISSUE TITLE
Is "inactivity time exceeded timeout" an issue?

### ISSUE THREAD

**Issue by tobiasfielitz** [fsouza/go-dockerclient#724]
We are using https://github.com/gliderlabs/logspout to forward logs from docker swarm to our ELK stack. _logspout_ uses go-dockerclient. I can see lots of `inactivity time exceeded timeout` errors in the logs and some logs never make it into ELK (I can see them using `docker service logs -f <service>` though).

I tried to read the code and understand when/why it happens, but I am not a go programmer unfortunately.

1. Is it something we have to worry about?
2. Is the go-dockerclient reconnecting automatically?
3. Why does it happen at all?

I am happy to provide more info if necessary. Would be nice to get a better understanding of this.

```
docker --version
Docker version 17.12.1-ce, build 7390fc6
```

**Comment by fsouza** [comment]
@tobiasfielitz hey, go-dockerclient doesn't reconnect, but I believe logspouts does reconnect? See this: https://github.com/gliderlabs/logspout/blob/f62d0c473a672aa5048335d7602984944d33bce6/router/pump.go#L227-L248

I don't think the logic on logspout's side is completely correct though, but it does seem like the inactivity timeout is configurable there, and you can disable it by setting the environment variable ``INACTIVITY_TIMEOUT`` to ``0`` (apparently that's the default value, but maybe there's some config on your side?0.

On a side note, if you still have data coming through, you shouldn't see inactivity timeouts.

**Comment by tobiasfielitz** [comment]
hey @fsouza thanks for the reply! 
If I understand correctly, I am getting these messages if there are no logs for the `INACTIVITY_TIMEOUT` period, but as soon as logspout reconnects (it does) it will pick up missing logs?
I guess I don't want to disable it completely as I am expecting it to be there for a reason.

**Comment by fsouza** [comment]
@tobiasfielitz yes, that seems to be the case, but I think the logic on logspout can be tunned to avoid losing log lines.

When reconnecting, logspout sets the "since" parameter to ``time.Now() - INACTIVITY_TIMEOUT``, so I believe there's a chance of  losing log lines that come immediately after (we could do some tests to prove it). If that's really the case, we could send a patch to logspout to do some padding on ``INACTIVITY_TIMEOUT`` (that would introduce the possibility of getting duplicated log lines though).
