### ISSUE TITLE
Sorry probs Noob Question, whats the diffrence between this project and the offical SDK?

### ISSUE THREAD

**Issue by brad-jones** [fsouza/go-dockerclient#731]
I have recently started learning go, and have also been using docker for ages so naturally I am building some interesting docker based tools, mainly for CI/CD purposes.

Anyway up until now I have been using the official SDK: https://docs.docker.com/develop/sdk/

I just stumbled across this project and note it's still pretty active, where as most other libs appear to be abandoned in favour of the official SDK.

So I am wondering what are the differences, pros, cons, why I would use one over the other, and generally what the roadmap for this project is like?

**Comment by fsouza** [comment]
Hey @brad-jones, thanks for bringing that up.

This project was created before Docker had an official Go SDK and is relatively active because it's still used in some tools such as tsuru, amazon-ecs-agent and nomad. IIRC, kubernetes also used to use go-dockerclient, but has now migrated to the official SDK.

For new projects, using the official SDK is probably more appropriate as go-dockerclient lags behind the official SDK (basically we add new stuff whenever people need them).

I hope that clarifies it. I'll also add a note to the README.
